services:
  db:
    container_name: task-manager-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5462:5432"
    healthcheck:   # check the help of the db
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
