CREATE TABLE tasks
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title       VARCHAR(255)                            NOT NULL,
  description TEXT,
  status      VARCHAR(50)                             NOT NULL,
  priority    VARCHAR(50)                             NOT NULL,
  created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  CONSTRAINT pk_tasks PRIMARY KEY (id)
);
