CREATE TABLE users
(
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username    VARCHAR(255),
  password    VARCHAR(255),
  authorities VARCHAR(255),
  CONSTRAINT pk_users PRIMARY KEY (id)
);


ALTER TABLE users
  ADD enabled BOOLEAN;

ALTER TABLE users
  ADD name VARCHAR(255);
