spring:
  application:
    name: Task Manager
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5462/task_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: on
  flyway:
    enabled: false
    baseline-on-migrate: off
    locations: classpath:db/migration

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

server:
  port: 8088
