# name
spring:
  application:
    name: Task Manager
# database config
  datasource:
    url: jdbc:postgresql://localhost:5462/task_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA config
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: on
  # flyway config
  flyway:
    enabled: false
    baseline-on-migrate: off
    locations: classpath:db/migration


jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
# port
server:
  port: 8088
